#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReglasDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EscuelaDB")]
	public partial class DataEscuelaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttblClase(tblClase instance);
    partial void UpdatetblClase(tblClase instance);
    partial void DeletetblClase(tblClase instance);
    partial void InserttblEstudiante(tblEstudiante instance);
    partial void UpdatetblEstudiante(tblEstudiante instance);
    partial void DeletetblEstudiante(tblEstudiante instance);
    partial void InserttblRegistro(tblRegistro instance);
    partial void UpdatetblRegistro(tblRegistro instance);
    partial void DeletetblRegistro(tblRegistro instance);
    #endregion
		
		public DataEscuelaDataContext() : 
				base(global::ReglasDemo.Properties.Settings.Default.EscuelaDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEscuelaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEscuelaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEscuelaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEscuelaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblClase> tblClase
		{
			get
			{
				return this.GetTable<tblClase>();
			}
		}
		
		public System.Data.Linq.Table<tblEstudiante> tblEstudiante
		{
			get
			{
				return this.GetTable<tblEstudiante>();
			}
		}
		
		public System.Data.Linq.Table<tblRegistro> tblRegistro
		{
			get
			{
				return this.GetTable<tblRegistro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblClase")]
	public partial class tblClase : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ClaseID;
		
		private string _NombreDeMateria;
		
		private string _DescripcionDeMateria;
		
		private double _CreditosHoras;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnClaseIDChanging(int value);
    partial void OnClaseIDChanged();
    partial void OnNombreDeMateriaChanging(string value);
    partial void OnNombreDeMateriaChanged();
    partial void OnDescripcionDeMateriaChanging(string value);
    partial void OnDescripcionDeMateriaChanged();
    partial void OnCreditosHorasChanging(double value);
    partial void OnCreditosHorasChanged();
    #endregion
		
		public tblClase()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaseID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ClaseID
		{
			get
			{
				return this._ClaseID;
			}
			set
			{
				if ((this._ClaseID != value))
				{
					this.OnClaseIDChanging(value);
					this.SendPropertyChanging();
					this._ClaseID = value;
					this.SendPropertyChanged("ClaseID");
					this.OnClaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDeMateria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NombreDeMateria
		{
			get
			{
				return this._NombreDeMateria;
			}
			set
			{
				if ((this._NombreDeMateria != value))
				{
					this.OnNombreDeMateriaChanging(value);
					this.SendPropertyChanging();
					this._NombreDeMateria = value;
					this.SendPropertyChanged("NombreDeMateria");
					this.OnNombreDeMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionDeMateria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DescripcionDeMateria
		{
			get
			{
				return this._DescripcionDeMateria;
			}
			set
			{
				if ((this._DescripcionDeMateria != value))
				{
					this.OnDescripcionDeMateriaChanging(value);
					this.SendPropertyChanging();
					this._DescripcionDeMateria = value;
					this.SendPropertyChanged("DescripcionDeMateria");
					this.OnDescripcionDeMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditosHoras", DbType="Float NOT NULL")]
		public double CreditosHoras
		{
			get
			{
				return this._CreditosHoras;
			}
			set
			{
				if ((this._CreditosHoras != value))
				{
					this.OnCreditosHorasChanging(value);
					this.SendPropertyChanging();
					this._CreditosHoras = value;
					this.SendPropertyChanged("CreditosHoras");
					this.OnCreditosHorasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEstudiante")]
	public partial class tblEstudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EstudianteID;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private char _Sexo;
		
		private double _Promedio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEstudianteIDChanging(int value);
    partial void OnEstudianteIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnSexoChanging(char value);
    partial void OnSexoChanged();
    partial void OnPromedioChanging(double value);
    partial void OnPromedioChanged();
    #endregion
		
		public tblEstudiante()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstudianteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EstudianteID
		{
			get
			{
				return this._EstudianteID;
			}
			set
			{
				if ((this._EstudianteID != value))
				{
					this.OnEstudianteIDChanging(value);
					this.SendPropertyChanging();
					this._EstudianteID = value;
					this.SendPropertyChanged("EstudianteID");
					this.OnEstudianteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1) NOT NULL")]
		public char Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promedio", DbType="Float NOT NULL")]
		public double Promedio
		{
			get
			{
				return this._Promedio;
			}
			set
			{
				if ((this._Promedio != value))
				{
					this.OnPromedioChanging(value);
					this.SendPropertyChanging();
					this._Promedio = value;
					this.SendPropertyChanged("Promedio");
					this.OnPromedioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRegistro")]
	public partial class tblRegistro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegistroID;
		
		private int _EstudianteID;
		
		private int _ClaseID;
		
		private string _Nivel;
		
		private string _Estatus;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegistroIDChanging(int value);
    partial void OnRegistroIDChanged();
    partial void OnEstudianteIDChanging(int value);
    partial void OnEstudianteIDChanged();
    partial void OnClaseIDChanging(int value);
    partial void OnClaseIDChanged();
    partial void OnNivelChanging(string value);
    partial void OnNivelChanged();
    partial void OnEstatusChanging(string value);
    partial void OnEstatusChanged();
    #endregion
		
		public tblRegistro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistroID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegistroID
		{
			get
			{
				return this._RegistroID;
			}
			set
			{
				if ((this._RegistroID != value))
				{
					this.OnRegistroIDChanging(value);
					this.SendPropertyChanging();
					this._RegistroID = value;
					this.SendPropertyChanged("RegistroID");
					this.OnRegistroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstudianteID", DbType="Int NOT NULL")]
		public int EstudianteID
		{
			get
			{
				return this._EstudianteID;
			}
			set
			{
				if ((this._EstudianteID != value))
				{
					this.OnEstudianteIDChanging(value);
					this.SendPropertyChanging();
					this._EstudianteID = value;
					this.SendPropertyChanged("EstudianteID");
					this.OnEstudianteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaseID", DbType="Int NOT NULL")]
		public int ClaseID
		{
			get
			{
				return this._ClaseID;
			}
			set
			{
				if ((this._ClaseID != value))
				{
					this.OnClaseIDChanging(value);
					this.SendPropertyChanging();
					this._ClaseID = value;
					this.SendPropertyChanged("ClaseID");
					this.OnClaseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="VarChar(2)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
