//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONPE_2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int person_id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string dni { get; set; }
        public int polling_place_id { get; set; }
    
        public virtual polling_place polling_place { get; set; }
    }
}
