//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONPE_2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class polling_place
    {
        public polling_place()
        {
            this.person = new HashSet<person>();
        }
    
        public int polling_place_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<person> person { get; set; }
    }
}
