//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEntity
    {
        public int car_id { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public Nullable<int> stock { get; set; }
    }
}
