//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_Northwind_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NORTHWNDEntities : DbContext
    {
        public NORTHWNDEntities()
            : base("name=NORTHWNDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CustomerDemographics> CustomerDemographics { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Shippers> Shippers { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Territories> Territories { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual ObjectResult<SF_GetEmployeeSales_Result> SF_GetEmployeeSales(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SF_GetEmployeeSales_Result>("SF_GetEmployeeSales", idParameter);
        }
    
        public virtual ObjectResult<SF_GetOrdersDetails_Result> SF_GetOrdersDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SF_GetOrdersDetails_Result>("SF_GetOrdersDetails");
        }
    
        public virtual ObjectResult<SF_GetOrdersFromCountryPerYear_Result> SF_GetOrdersFromCountryPerYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SF_GetOrdersFromCountryPerYear_Result>("SF_GetOrdersFromCountryPerYear");
        }
    
        public virtual ObjectResult<SF_GetSalesPerPeriod_Result> SF_GetSalesPerPeriod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SF_GetSalesPerPeriod_Result>("SF_GetSalesPerPeriod");
        }
    }
}
