//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10_Northwind_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string user_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public Nullable<int> role { get; set; }
    }
}
