package com.upc.proyectos.hibernatesqlserver.entidades;
// Generated 05/06/2016 06:54:09 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements Serializable {

    private int categoryId;
    private String categoryName;
    private String description;
    private byte[] picture;
    private Set<Products> productses = new HashSet<Products>(0);

    public Categories() {
    }

    public Categories(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }

    public Categories(int categoryId, String categoryName, String description, byte[] picture, Set<Products> productses) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
        this.description = description;
        this.picture = picture;
        this.productses = productses;
    }

    public int getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return this.categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public byte[] getPicture() {
        return this.picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    public Set<Products> getProductses() {
        return this.productses;
    }

    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }
}
