//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado_Net.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int car_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int car_id {
            get {
                return this.car_idField;
            }
            set {
                if ((this.car_idField.Equals(value) != true)) {
                    this.car_idField = value;
                    this.RaisePropertyChanged("car_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        Ado_Net.ServiceReference1.ListResponse List(Ado_Net.ServiceReference1.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.ListResponse> ListAsync(Ado_Net.ServiceReference1.ListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento car del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        Ado_Net.ServiceReference1.CreateResponse Create(Ado_Net.ServiceReference1.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.CreateResponse> CreateAsync(Ado_Net.ServiceReference1.CreateRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento FindResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        Ado_Net.ServiceReference1.FindResponse Find(Ado_Net.ServiceReference1.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.FindResponse> FindAsync(Ado_Net.ServiceReference1.FindRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento car del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        Ado_Net.ServiceReference1.EditResponse Edit(Ado_Net.ServiceReference1.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.EditResponse> EditAsync(Ado_Net.ServiceReference1.EditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(Ado_Net.ServiceReference1.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRequestBody {
        
        public ListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(Ado_Net.ServiceReference1.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ado_Net.ServiceReference1.Car[] ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(Ado_Net.ServiceReference1.Car[] ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(Ado_Net.ServiceReference1.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ado_Net.ServiceReference1.Car car;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(Ado_Net.ServiceReference1.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(Ado_Net.ServiceReference1.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateResult;
        
        public CreateResponseBody() {
        }
        
        public CreateResponseBody(bool CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(Ado_Net.ServiceReference1.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> id;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(System.Nullable<int> id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(Ado_Net.ServiceReference1.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ado_Net.ServiceReference1.Car FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(Ado_Net.ServiceReference1.Car FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Edit", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.EditRequestBody Body;
        
        public EditRequest() {
        }
        
        public EditRequest(Ado_Net.ServiceReference1.EditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ado_Net.ServiceReference1.Car car;
        
        public EditRequestBody() {
        }
        
        public EditRequestBody(Ado_Net.ServiceReference1.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ado_Net.ServiceReference1.EditResponseBody Body;
        
        public EditResponse() {
        }
        
        public EditResponse(Ado_Net.ServiceReference1.EditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EditResult;
        
        public EditResponseBody() {
        }
        
        public EditResponseBody(bool EditResult) {
            this.EditResult = EditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Ado_Net.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Ado_Net.ServiceReference1.Service1Soap>, Ado_Net.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ado_Net.ServiceReference1.ListResponse Ado_Net.ServiceReference1.Service1Soap.List(Ado_Net.ServiceReference1.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public Ado_Net.ServiceReference1.Car[] List() {
            Ado_Net.ServiceReference1.ListRequest inValue = new Ado_Net.ServiceReference1.ListRequest();
            inValue.Body = new Ado_Net.ServiceReference1.ListRequestBody();
            Ado_Net.ServiceReference1.ListResponse retVal = ((Ado_Net.ServiceReference1.Service1Soap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.ListResponse> Ado_Net.ServiceReference1.Service1Soap.ListAsync(Ado_Net.ServiceReference1.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ado_Net.ServiceReference1.ListResponse> ListAsync() {
            Ado_Net.ServiceReference1.ListRequest inValue = new Ado_Net.ServiceReference1.ListRequest();
            inValue.Body = new Ado_Net.ServiceReference1.ListRequestBody();
            return ((Ado_Net.ServiceReference1.Service1Soap)(this)).ListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ado_Net.ServiceReference1.CreateResponse Ado_Net.ServiceReference1.Service1Soap.Create(Ado_Net.ServiceReference1.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public bool Create(Ado_Net.ServiceReference1.Car car) {
            Ado_Net.ServiceReference1.CreateRequest inValue = new Ado_Net.ServiceReference1.CreateRequest();
            inValue.Body = new Ado_Net.ServiceReference1.CreateRequestBody();
            inValue.Body.car = car;
            Ado_Net.ServiceReference1.CreateResponse retVal = ((Ado_Net.ServiceReference1.Service1Soap)(this)).Create(inValue);
            return retVal.Body.CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.CreateResponse> Ado_Net.ServiceReference1.Service1Soap.CreateAsync(Ado_Net.ServiceReference1.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ado_Net.ServiceReference1.CreateResponse> CreateAsync(Ado_Net.ServiceReference1.Car car) {
            Ado_Net.ServiceReference1.CreateRequest inValue = new Ado_Net.ServiceReference1.CreateRequest();
            inValue.Body = new Ado_Net.ServiceReference1.CreateRequestBody();
            inValue.Body.car = car;
            return ((Ado_Net.ServiceReference1.Service1Soap)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ado_Net.ServiceReference1.FindResponse Ado_Net.ServiceReference1.Service1Soap.Find(Ado_Net.ServiceReference1.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public Ado_Net.ServiceReference1.Car Find(System.Nullable<int> id) {
            Ado_Net.ServiceReference1.FindRequest inValue = new Ado_Net.ServiceReference1.FindRequest();
            inValue.Body = new Ado_Net.ServiceReference1.FindRequestBody();
            inValue.Body.id = id;
            Ado_Net.ServiceReference1.FindResponse retVal = ((Ado_Net.ServiceReference1.Service1Soap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.FindResponse> Ado_Net.ServiceReference1.Service1Soap.FindAsync(Ado_Net.ServiceReference1.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ado_Net.ServiceReference1.FindResponse> FindAsync(System.Nullable<int> id) {
            Ado_Net.ServiceReference1.FindRequest inValue = new Ado_Net.ServiceReference1.FindRequest();
            inValue.Body = new Ado_Net.ServiceReference1.FindRequestBody();
            inValue.Body.id = id;
            return ((Ado_Net.ServiceReference1.Service1Soap)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ado_Net.ServiceReference1.EditResponse Ado_Net.ServiceReference1.Service1Soap.Edit(Ado_Net.ServiceReference1.EditRequest request) {
            return base.Channel.Edit(request);
        }
        
        public bool Edit(Ado_Net.ServiceReference1.Car car) {
            Ado_Net.ServiceReference1.EditRequest inValue = new Ado_Net.ServiceReference1.EditRequest();
            inValue.Body = new Ado_Net.ServiceReference1.EditRequestBody();
            inValue.Body.car = car;
            Ado_Net.ServiceReference1.EditResponse retVal = ((Ado_Net.ServiceReference1.Service1Soap)(this)).Edit(inValue);
            return retVal.Body.EditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ado_Net.ServiceReference1.EditResponse> Ado_Net.ServiceReference1.Service1Soap.EditAsync(Ado_Net.ServiceReference1.EditRequest request) {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ado_Net.ServiceReference1.EditResponse> EditAsync(Ado_Net.ServiceReference1.Car car) {
            Ado_Net.ServiceReference1.EditRequest inValue = new Ado_Net.ServiceReference1.EditRequest();
            inValue.Body = new Ado_Net.ServiceReference1.EditRequestBody();
            inValue.Body.car = car;
            return ((Ado_Net.ServiceReference1.Service1Soap)(this)).EditAsync(inValue);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
