<?xml version="1.0" encoding="utf-8"?><Database Name="EscuelaDB" Class="DataEscuelaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LENOVO-PC\LENOVO;Initial Catalog=EscuelaDB;Integrated Security=True" SettingsObjectName="ReglasDemo.Properties.Settings" SettingsPropertyName="EscuelaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblClase" Member="tblClase">
    <Type Name="tblClase">
      <Column Name="ClaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreDeMateria" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionDeMateria" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreditosHoras" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblEstudiante" Member="tblEstudiante">
    <Type Name="tblEstudiante">
      <Column Name="EstudianteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Promedio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblRegistro" Member="tblRegistro">
    <Type Name="tblRegistro">
      <Column Name="RegistroID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstudianteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nivel" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>